#launch requirements/mariadb nginx and wordpress
version: "3.7"
volumes:
    wordpress:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "$HOME/data/wordpress"
    mariadb:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "$HOME/data/mariadb"
networks:
    backend:
        driver: bridge
services:
    mariadb:
        container_name: mariadb
        image: mariadb
        networks:
            - backend
        build: ./requirements/mariadb
        #dockerfile: Dockerfile
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - wordpress:/var/www/html
        networks:
            - backend
        depends_on:
            - wordpress
        build: ./requirements/nginx
        #dockerfile: Dockerfile
        env_file: .env
        ports:
            - "443:443"
        restart: on-failure
    wordpress:
        container_name: wordpress
        image: wordpress
        env_file: .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - backend
        build: ./requirements/wordpress
        #dockerfile: Dockerfile
        depends_on:
            - mariadb
        restart: on-failure
