#Wordpress/PHP dockerfile
FROM alpine:3.15

RUN apk update && apk add php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session
LABEL version="1.0"
LABEL description="Wordpress Server"
#set up wordpress
