#Wordpress/PHP dockerfile
FROM alpine:3.15

RUN apk update && apk add mariadb-client wget
RUN apk add php7 php-fpm php-mysqli
LABEL version="1.0"
LABEL description="Wordpress Server"
RUN wget https://wordpress.org/latest.tar.gz -P /var/www
RUN cd /var/www && tar -xvf latest.tar.gz && rm latest.tar.gz
RUN chown -R root:root /var/www/wordpress
#php config

#install wordpresscli
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
COPY ./conf/php-fpm.conf /etc/php/7.3/pool.d
COPY ./tools/wp-config.php /var/www/
COPY ./tools/init.sh /tmp/init.sh
ENTRYPOINT ["sh", "/tmp/init.sh"]