#Wordpress/PHP dockerfile
FROM alpine:3.15

RUN apk update && apk add mariadb-client wget
RUN apk add lighttpd php7-common php7-session php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom php7-simplexml
LABEL version="1.0"
LABEL description="Wordpress Server"
#php config

#install wordpresscli
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY ./tools/init.sh /tmp/init.sh
ENTRYPOINT ["sh", "/tmp/init.sh"]